In [24]:
import pandas as pd

dfCLOC_app = pd.read_csv('../cloc/cloc_app_result.csv')
dfCLOC_core = pd.read_csv('../cloc/cloc_core_result.csv')
dfCLOC_app.head()

,file_name,file_path,cloc
0,AgrimateApplication.kt,C:\Users\dewat\Desktop\Project Skripsi Agrimat...,0
1,BaseViewModel.kt,C:\Users\dewat\Desktop\Project Skripsi Agrimat...,0
2,FormHandler.kt,C:\Users\dewat\Desktop\Project Skripsi Agrimat...,0
3,AppModule.kt,C:\Users\dewat\Desktop\Project Skripsi Agrimat...,0
4,LibraryModule.kt,C:\Users\dewat\Desktop\Project Skripsi Agrimat...,0

In [25]:
# ubah nama kolom 'Nama File' menjadi 'Nama Kelas' di kedua dataframe
dfCLOC_app.rename(columns={'file_name': 'Nama Kelas'}, inplace=True)
dfCLOC_core.rename(columns={'file_name': 'Nama Kelas'}, inplace=True)

# hapus kolom file_path di kedua dataframe
dfCLOC_app.drop(columns=['file_path'], inplace=True)
dfCLOC_core.drop(columns=['file_path'], inplace=True)

# ubah nama kolom 'cloc' menjadi 'CLOC' di kedua dataframe
dfCLOC_app.rename(columns={'cloc': 'CLOC'}, inplace=True)
dfCLOC_core.rename(columns={'cloc': 'CLOC'}, inplace=True)

In [26]:
dfCLOC_app

                 Nama Kelas  CLOC
0    AgrimateApplication.kt     0
1          BaseViewModel.kt     0
2            FormHandler.kt     0
3              AppModule.kt     0
4          LibraryModule.kt     0
..                      ...   ...
160          FormatUtils.kt     0
161    PermissionManager.kt     0
162            TimeUtils.kt     0
163              UiUtils.kt     0
164      ValidationUtils.kt     0

[165 rows x 2 columns]

In [27]:
dfCLOC_core

                      Nama Kelas  CLOC
0          AuthRepositoryImpl.kt     0
1     CommodityRepositoryImpl.kt     0
2     DataStoreRepositoryImpl.kt     0
3    FarmerLandRepositoryImpl.kt     0
4       HarvestRepositoryImpl.kt     0
..                           ...   ...
125           AuthInterceptor.kt     0
126                ErrorUtils.kt     0
127                    Mapper.kt     0
128               RequestFlow.kt     0
129                  Resource.kt     0

[130 rows x 2 columns]

In [28]:
# gabung semua dataframe dfCLOC_app dan dfCLOC_core menjadi dfCLOC
dfCLOC = pd.concat([dfCLOC_app, dfCLOC_core], ignore_index=True)

In [29]:
dfCLOC

                 Nama Kelas  CLOC
0    AgrimateApplication.kt     0
1          BaseViewModel.kt     0
2            FormHandler.kt     0
3              AppModule.kt     0
4          LibraryModule.kt     0
..                      ...   ...
290      AuthInterceptor.kt     0
291           ErrorUtils.kt     0
292               Mapper.kt     0
293          RequestFlow.kt     0
294             Resource.kt     0

[295 rows x 2 columns]

In [30]:
# export dfCLOC ke file excel
dfCLOC.to_excel('cloc_all_result.xlsx', index=False)