# CC App

In [8]:
import pandas as pd

dfApp = pd.read_csv('cc_per_file.csv')
dfApp.head()

,file_name,file_path,cyclomatic_complexity
0,ExampleInstrumentedTest.kt,C:\Users\dewat\Desktop\Project Skripsi Agrimat...,1
1,AgrimateApplication.kt,C:\Users\dewat\Desktop\Project Skripsi Agrimat...,1
2,BaseViewModel.kt,C:\Users\dewat\Desktop\Project Skripsi Agrimat...,1
3,FormHandler.kt,C:\Users\dewat\Desktop\Project Skripsi Agrimat...,1
4,AppModule.kt,C:\Users\dewat\Desktop\Project Skripsi Agrimat...,1

In [9]:
# ubah nama function_count menjadi V(g)
dfApp = dfApp.rename(columns={'cyclomatic_complexity': 'V(g)'})

# ubah nama file_name menjadi Nama Kelas
dfApp = dfApp.rename(columns={'file_name': 'Nama Kelas'})

# hapus kolom file_path
dfApp = dfApp.drop(columns=['file_path'])

1 - 10
Risiko Minimal
11 - 20
Risiko Sedang
21 - 50
Risiko Tinggi
> 50
Risiko Sangat tinggi

In [10]:
# hapus nama kelas yang tidak ada 'ExampleInstrumentedTest.kt', 'ExampleUnitTest.kt', 'FormatUtilsTest.kt', 'DateUtilsTest.kt'
dfApp = dfApp[~dfApp['Nama Kelas'].isin(['ExampleInstrumentedTest.kt', 'ExampleUnitTest.kt', 'FormatUtilsTest.kt', 'DateUtilsTest.kt'])]
dfApp.head()

               Nama Kelas  V(g)
1  AgrimateApplication.kt     1
2        BaseViewModel.kt     1
3          FormHandler.kt     1
4            AppModule.kt     1
5        LibraryModule.kt     1

In [11]:
# import to excel
dfApp.to_excel('cc_result_core_final.xlsx', index=False)